version: '3.4'

services:
  db:
    image: arm64v8/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: 'springboot-pedidex'
    ports:
      - "3306:3306"