package com.acme.pedidex.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.*;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

//@NoArgsConstructor
//@RequiredArgsConstructor
//@EqualsAndHashCode(onlyExplicitlyIncluded = true)
//@ToString(onlyExplicitlyIncluded = true)
//@Getter
//@Setter
// About data https://projectlombok.org/features/Data

@Data
@RequiredArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "category")
public class Category implements Serializable {

    // doenst put nonnull because id is generated by database. If put nonnull so than change the test and pass a val on ids
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Include
    private Long id;
    @NonNull // to explicit that field is required on constructor
    private String name;
    @JsonIgnore
    @ManyToMany(mappedBy = "categories")
    @ToString.Exclude // if want to remove from to string to eliminate overhead in subsequents querys
    @Setter(AccessLevel.NONE) // if dont want to allow setter
    private Set<Product> products = new HashSet<>();
    public Set<Product> getProducts() {
        return products;
    }
}
